### ISSUE TITLE
Move the ASCII art to a separate file

### ISSUE THREAD

**Issue by arijit79** [mufeedvh/binserve#10]
I was inspecting your sources, The ASCII art didn't looked good in the middle of the source code. It would be better if you move it to a separate file or maybe make it a `const`. Also the line that tells about the host and port could be put along with the ASCII art. You should use the `include_str!` macro to include it into the source code during compilation and use it in the `println!` also specifying the host and port

**Comment by arijit79** [comment]
I was inspecting your sources, The ASCII art didn't looked good in the middle of the source code. It would be better if you move it to a separate file or maybe make it a `const`. Also the that tells about the host and port could be put along with the ASCII art

**Comment by mufeedvh** [comment]
Hey @arijit79, thanks for raising this issue! This is indeed a good way to do, I will make a banner file that gets printed out with `include_str!` during execution. It does seem messy inside the code, I will definitely push this change soon! :heart::raised_hands:

**Comment by arijit79** [comment]
Also, unrelated to this issue, but something related to formatting is that your files in the static folder are all in one line, you should probably format them according HTML writing styles. If you use an IDE like VSCode or Atom, they have plugins to improve the formatting of HTML

**Comment by mufeedvh** [comment]
I just made it one-liners because it's default generated templates and short in LOC. But yes it would improve readability in format, thank you for the request, I will definitely look into this as well. :smiley::+1:

**Comment by arijit79** [comment]
I will filing a PR to fix the HTML issue

**Comment by mufeedvh** [comment]
Awesome @arijit79, thank you! :heart::raised_hands:
