### ISSUE TITLE
Feature request: optional HTTPS support with automatically generated self-signed certificate

### ISSUE THREAD

**Issue by ngirard** [mufeedvh/binserve#17]
Hi,

I'd be much interested in having `binserve` provide HTTPS support with both automatically generated self-signed certificate or cert/key file as input.

As far as I know it cannot be found within the Rust command-line tools. For instance, Miniserve [has yet](https://github.com/svenstaro/miniserve/issues/282) to implement it.

Cheers, and thanks for your work and dedication !

**Comment by mufeedvh** [comment]
Hey @ngirard, thank you for the feature request! I actually implemented this at first but the generated self-signed certificate verification made me drop the idea as it shows up as insecure in browsers but this feature is indeed required. I will implement a **Let's Encrypt** TLS certificate as default and add automatic self-signed certificate generation and custom cert/key file input support.

**If you/anyone wants to do this with the current version**: You can use a reverse proxy server (Nginx/Apache) to achieve this.

I will implement this feature in the next release. :+1:

Thank You! :heart::raised_hands:

**Comment by ngirard** [comment]
Wow, that would be great !

**Comment by erlend-sh** [comment]
Maybe mention the support for Let’s Encrypt more clearly in the readme, like [Caddy does](https://github.com/caddyserver/caddy#features)? I was looking specifically for LE support and only found out about it via this issue.
