### ISSUE TITLE
Append *.html files with .hbs extension

### ISSUE THREAD

**Issue by arijit79** [mufeedvh/binserve#18]
According to some of the information on handlebars, you should add a `.hbs` extension. You can replace all .`.html` with it or add it after the `.html`. This change can help some IDEs such as VSCode which has both HTML filetype as well as HBS filetype. You should also change the filenames in the `setup_static` function as well as `setup_404` function

**Comment by mufeedvh** [comment]
This feature has been implemented!

v0.2.0 Released! :tada:
