### ISSUE TITLE
Enhancement: Authentication and authorization

### ISSUE THREAD

**Issue by danmx** [mufeedvh/binserve#2]
It would be great if you could specify which paths are available and for who (authN+Z)

**Comment by mufeedvh** [comment]
Hello @danmx, thank you for this feature request! `binserve` being a **static web server**, do we need dynamic features like this? It's just static responses so authorizations for different users isn't required anyway. Although upon reading your request I got an idea, the `assets` directory can be used as a _download directory_ and we can maybe allow downloads with authentication but that would not fit the "static" structure tho.

This being a low priority feature, I am closing this issue but I will keep this in mind for future releases.

Thank You! :heart::raised_hands:
