### ISSUE TITLE
Enhacement: Subresource Integrity support

### ISSUE THREAD

**Issue by danmx** [mufeedvh/binserve#3]
Support for [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), automatically generating hashes for served static content, would boost the security.

**Comment by mufeedvh** [comment]
Hey @danmx, this is an interesting feature request! I don't know if this is overengineering for a static web server but I would like to include [**CORS**](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers in the next release so I will definitely think about adding both.

Thank You for the awesome feature request! :heart::raised_hands:
