### ISSUE TITLE
Enhancement: exporting Prometheus metrics

### ISSUE THREAD

**Issue by danmx** [mufeedvh/binserve#5]
Exposing [Prometheus](https://prometheus.io/) metrics would help productionize this tool. It seems there's already a crate ([actix-web-prom](https://github.com/nlopes/actix-web-prom) that interacts with actix-web.

**Comment by mufeedvh** [comment]
Hey @danmx, thanks for the enhancement request. This does seem like a cool idea to implement but `binserve` being a static web server, do we actually need a metrics tool? It's more applicable to a dynamic web service but I'll definitely think about this! :raised_hands:

**Comment by danmx** [comment]
You always need monitoring so metrics are needed. For example, I would want to know what's the request latency even when serving static content to make sure it's not increasing with more traffic or how many requests per second do you have to actually measure the traffic.

**Comment by mufeedvh** [comment]
@danmx Ah, that makes sense! That would be an awesome feature as well! :100: 

> This will be included in the next release or **v0.3.0**.

Thank You for this amazing feature request! :heart::raised_hands:

**Comment by mufeedvh** [comment]
This feature has been implemented!

v0.2.0 Released! :tada:
