### ISSUE TITLE
Unable to cargo build on MacOS

### ISSUE THREAD

**Issue by danmx** [mufeedvh/binserve#7]
I'm unable to build the binary on my mac.

Build:
```console
$ cargo build
    Updating crates.io index
 Downloading actix-web v3.0.2
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.0.2/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

System:
```console
$ uname -a
Darwin xxx 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

Cargo version:
```console
$ cargo --version
cargo 1.30.0 (a1a4ad372 2018-11-02)
```

**Comment by mufeedvh** [comment]
Hey @danmx, thank you for raising this issue. I am on Linux so I wasn't able to cross-compile for MacOS, I tried some [crusty ways](https://www.reddit.com/r/rust/comments/6rxoty/tutorial_cross_compiling_from_linux_for_osx/) to compile it and that was the weird `x86_64-apple-darwin15-gcc` linker in `.cargo/config`. I removed it now as @ivanmoskalev suggested and it compiles successfully in MacOS.

I have uploaded the [**binary**](https://github.com/mufeedvh/binserve/releases/download/v0.1.0/binserve-v0.1.0-x86_64-macos) for MacOS in Releases.

Thank You @danmx @ivanmoskalev! :heart::raised_hands:
