### ISSUE TITLE
Integration with other Rust libraries

### ISSUE THREAD

**Issue by arijit79** [mufeedvh/binserve#8]
I would not like to call this an issue (maybe it is) but rather a question. So you describe in the README on how you can use the `template_variables` key in the `binserve.json` file to serve variables. This got me a question about how can someone integrate with other Rust libraries like Diesel so that it can interact with a database or maybe something even simple like getting some information from the URL.

I didn't got any links to Documentation and the README didn't said enough so I filled this issue

**Comment by mufeedvh** [comment]
Thank you @arijit79 for raising this issue. That would be an awesome feature but this project is meant to be a **static web server** thus won't offer any dynamic features such as interacting with a database or dynamic variables.

**The usage here is only applied to static template variables:**
- Website Title
- Meta Description
- Meta Keywords
- etc.

I also have a small plan to write a dynamic web framework on top of this, not sure about the plan but definitely thinking about it with the features you mentioned! :raised_hands:
