### ISSUE TITLE
Use actix_web::main for main function

### ISSUE THREAD

**Issue by arijit79** [mufeedvh/binserve#9]
The actix_web's newest stable release re-exports `actix_rt::main`. So you probably should change your `main` function to this

``` rust
#[actix_web::main]
async fn main() -> std::io::Result<()>  {
```
And append `main` to the `use` line of actix_web in the `main.rs` file.

You should also probably remove `actix-rt` from the dependencies list in your `Cargo.toml` because I do not see any other use for it.

I should have filled up a PR but I didn't had the time to fork, change and file it. Also I didn't fully studied your codebase

**Comment by mufeedvh** [comment]
Thank you @arijit79 for raising this issue, I've fixed it in https://github.com/mufeedvh/binserve/commit/04561b29bbf60aff46c4a4a7552fa64e6eb0388a. :heart::raised_hands:
